baseurl = "http://kicad-pcb.org/"
languageCode = "en-us"
title = "KiCad EDA"
canonifyurls = true
layoutdir = "layouts"
theme = "startbootstrap-clean-blog"

[params]
	DateForm = "Mon, Jan 2, 2006"
	Description = "A Cross Platform and Open Source Electronics Design Automation Suite"
	Author = "The KiCad editors"
	email = "foo@bar.com"
	Ganalytics = "XX-00000000-0"

[[params.social]]
  title = "twitter"
  url = "https://twitter.com/kicad_pcb"
[[params.social]]
  title = "github"
  url = "https://github.com/KiCad"
[[params.social]]
  title = "facebook"
  url = "https://www.facebook.com/kicadpcb"

[[menu.main]]
  name     = "Blog"
  url      = "/post"
  weight   = -200

[[menu.main]]
  name     = "Download"
  url      = "/download"
  weight   = 10


[[menu.main]]
    name   = "Community"
    weight = 10
[[menu.main]]
    parent = "Community"
    name   = "Forum"
    url    = "http://forum.kicad.info/"
    weight = 10
[[menu.main]]
    parent = "Community"
    name   = "kicad.jp"
    url    = "http://kicad.jp/"
    weight = 10


[[menu.main]]
  name     = "Documentation"
  url      = "http://docs.kicad-pcb.org/"
  weight   = 0

[[menu.main]]
    parent = "Documentation"
    name   = "External Tools"
    url    = "http://www.kicad-pcb.org/display/KICAD/External+Tools"
    weight = 10
[[menu.main]]
    parent = "Documentation"
    name   = "Users's Manual"
    weight = 20
[[menu.main]]
    parent = "Documentation"
    name   = "Tutorials"
    url    = "http://www.kicad-pcb.org/display/KICAD/Tutorials"
    weight = 30
[[menu.main]]
    parent = "Documentation"
    name   = "Miration from old stable"
    url    = "http://www.kicad-pcb.org/display/KICAD/Migration+from+old+stable+to+latest"
    weight = 40
[[menu.main]]
    parent = "Documentation"
    name   = "File Formats"
    url    = "http://www.kicad-pcb.org/display/KICAD/File+Formats"
    weight = 50
[[menu.main]]
    parent = "Documentation"
    name   = "FAQ"
    url    = "http://www.kicad-pcb.org/display/KICAD/Frequently+Asked+Questions"
    weight = 60
