baseurl = "http://kicad-pcb.org/"
languageCode = "en-us"
title = "KiCad EDA"
canonifyurls = true
layoutdir = "layouts"
theme = "startbootstrap-clean-blog"

[params]
	DateForm = "Mon, Jan 2, 2006"
	Description = "A Cross Platform and Open Source Electronics Design Automation Suite"
	Author = "The KiCad editors"
	email = "foo@bar.com"
	Ganalytics = "XX-00000000-0"

[[params.social]]
  title = "twitter"
  url = "https://twitter.com/kicad_pcb"
[[params.social]]
  title = "github"
  url = "https://github.com/KiCad"
[[params.social]]
  title = "facebook"
  url = "https://www.facebook.com/kicadpcb"

[[menu.main]]
  name = "Documentation"
  url = "http://docs.kicad-pcb.org/"
  weight = 0

[[menu.main]]
    parent = "Documentation"
    name   = "KiCad"
    weight = 10
[[menu.main]]
    parent = "Documentation"
    name   = "Eeschema"
    weight = 20
[[menu.main]]
    parent = "Documentation"
    name   = "Pcbnew"
    weight = 30
[[menu.main]]
    parent = "Documentation"
    name   = "GerbView"
    weight = 40
[[menu.main]]
    parent = "Documentation"
    name   = "Bitmap2Component"
    weight = 50
[[menu.main]]
    parent = "Documentation"
    name   = "Pl_editor"
    weight = 60
